services:
  - type: web
    name: careerlens
    env: node
    region: oregon
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
